### ISSUE TITLE
Some (maybe beyond a certain size?) videos don't download

### ISSUE THREAD

**Issue by Ryujinra** [tophf/mpiv#16]
I can reproduce on Instagram at least. Visit: [instagram.com/instagram](https://www.instagram.com/instagram). Hover the first IGTV video (currently the 9th post). Hit the download shortcut. Nothing will happen. Waiting for the full video to buffer or get near the end doesn't change the behavior. Right click > Save As works as expected. 

Scroll to the next IGTV video, (it's shorter), and the download key works properly.

I'm not sure if this only effects IGTV videos, but I can't find a large/long normal Instagram video ATM to test. I imagine it would also fail on some of them if it is a size issue. I didn't test other sites but it might be reproducible for other videos. I'll try to reproduce elsewhere soon.

**Comment by tophf** [comment]
The video is indeed bigger than what is allowed to transfer inside extension messaging so this is a bug of your *monkey manager. I thought I've fixed this in Violentmonkey but evidently one small detail is still missing, which will be fixed in the next version of Violentmonkey. You can report the issue to TM's author yourself.

**Comment by tophf** [comment]
Uhm, I've switched to GM_download so TM is working fine now even if it didn't before, I'm too lazy to verify. As for VM, it had [another bug](https://github.com/violentmonkey/violentmonkey/pull/897) which I just fixed so you can try to sideload [my dev build](https://puu.sh/FhJbE/c27678f059.zip) until the fix is released.

**Comment by Ryujinra** [comment]
This works for me now with the latest master and the normal build of VM; didn't need to use your fix. What was the bug in VM? I can test your VM fix, but I don't know what is  broken.

**Comment by tophf** [comment]
That bug would only manifest in the old version of MPIV before I switched to GM_download e.g. the previous commit 60e0d722 and any earlier one didn't download that big video in the current Violentmonkey.

**Comment by Ryujinra** [comment]
Can't reproduce with the latest VM version on Firefox Addons; larger videos work for me with the latest mpiv.

**Comment by tophf** [comment]
Yeah, looks like it's a Chrome-only bug.
