### ISSUE TITLE
Request: popup for webp image files

### ISSUE THREAD

**Issue by tanakah** [tophf/mpiv#22]
Would it be possible to load webp image files when hovering them?

**Comment by tophf** [comment]
They're already supported. Be more specific.

**Comment by tanakah** [comment]
I'm using mpiv ver 1.1.6
for instance, it is possible to load and popup the jpg image in this website when hovering it. On the other hand, not possible to load the webp image for some reason.
https://developers.google.com/speed/webp/gallery1?hl=ja
![コメント 2020-03-14 151427](https://user-images.githubusercontent.com/683605/76676410-85de5980-6606-11ea-9ffa-1648da2fb8c5.png)

**Comment by tophf** [comment]
It wasn't shown because the generic thumbnail expansion rule indeed didn't support `webp`. Fixed in the current master branch which you can test by reinstalling from the [direct URL](https://github.com/tophf/mpiv/raw/master/script.user.js) or by copypasting the source code into the userscript manager.

**Comment by tanakah** [comment]
thank you very much, it works very well!
