### ISSUE TITLE
MPIV host rule repository shutting down

### ISSUE THREAD

**Issue by nimuxoha** [tophf/mpiv#42]
The original developer of MPIV seems to have deleted their GreasyFork account which also caused the deletion of their scripts there.
Recently a notice appeared on their host rule repo at https://w9p.co/userscripts/mpiv/manage_rules.html saying the site will shut down.
>  This site will shut down on January 31st. 

I couldn't find out if you are aware of it yet (and how this fork will cope with that). In case you are not, here you go :)

**Comment by tophf** [comment]
Thanks. This script doesn't depend on the original site so it'll keep working. I'll check the rules and probably incorporate those that still work.

**Comment by darkred** [comment]
For reference, here is the latest snapshot (Dec 20 2020) of the deleted GreasyFork MPIV page: 
http://web.archive.org/web/20201220173334/https://greasyfork.org/en/scripts/404-mouseover-popup-image-viewer

In there it has at some point:

> Feel free to fork. **Snapshot of website [here](https://w9p.co/userscripts/mpiv/mpiv.zip)**

of which the linked zip contains a snapshot of late 2017 (I attach it here: [mpiv.zip](https://github.com/tophf/mpiv/files/5838672/mpiv.zip) )

**Comment by mikhoul** [comment]
@tophf   Here's the full backup of the website, it can be forked without any problem the author said,

It's a simple HTML website so ti could be cleaned-up and hosted here on Github.

[mpiv.zip](https://github.com/tophf/mpiv/files/5838698/mpiv.zip)


Regards :octocat:

**Comment by darkred** [comment]
@mikhoul the .zip you posted is the same as as mine (late 2017).

---

The best would be to have a current/up-to-date offline copy of the site. 
So I used wget as follows: `wget --mirror --convert-links --adjust-extension --page-requisites https://w9p.co/userscripts/mpiv`
and here it is: [mpiv-current.zip](https://github.com/tophf/mpiv/files/5839188/mpiv-current.zip)

**Comment by darkred** [comment]
@tophf 
Maybe we could use GitHub Pages (https://pages.github.com/) to host the website in GitHub directly from your repo,
using the [mpiv-current.zip](https://github.com/tophf/mpiv/files/5839188/mpiv-current.zip) content I downloaded using Wget ?

**Comment by tophf** [comment]
I won't be maintaining site.

**Comment by mikhoul** [comment]
@darkred   You could publish the website like you said on Github and link here to the repo of @tophf and @tophf  could put a link to your website .

Since @tophf  is involved in a lot of actives projects I understand that his schedule is full.

This way the ressource would be available to the users of MPIV.  :smile_cat:

**Comment by darkred** [comment]
> 😸

No, on second thought I find my suggestion is not worthy, and so, I ask sorry to @tophf for making that suggestion. 

First of all, I didn't think mind that having such a page requires maintenance on a constant basis.
I merely thought it to be as simple to publishing+pushing the content there as `https://tophf.github.io/mpiv` as a "mirror", and leave it be as it is, just like `https://userscripts-mirror.org/scripts/show/109262` .
*BUT, the original site `https://w9p.co/userscripts/mpiv/manage_rules.html?add` had the rule submitting procedure protected behind a captcha, apparently as a security measure to protect from spam, vandalizing, etc. 
Plus, I'm sure it will end up being burden, since the MPIV author has eventually abandoned everything, the script itself, the support, the GF page, the website, everything.*

---

The .zip resource I posted will remain for any users interested.
An alternative mirror is the Internet Archive:
http://web.archive.org/web/20210116170009/https://w9p.co/userscripts/mpiv/manage_rules.html
http://web.archive.org/web/20210116170002/https://w9p.co/userscripts/mpiv/more_host_rules.html

**Comment by tophf** [comment]
The site's contents can be transferred to this repository's Wiki so anyone can do it.

**Comment by darkred** [comment]
Yes, it would be simple to transfer the site's MPIV documentation to this repo's wiki. I could try to make a PR.

But, I was referring to the difficulties of also providing a rule submitting form, and maintaining a rule repository.

**Comment by tophf** [comment]
Wiki can be edited directly by anyone, including the rules.

**Comment by darkred** [comment]
I made an effort and converted the 4 main pages into wiki (HTML->Markdown)  : 
https://github.com/tophf/mpiv/wiki

**Comment by tophf** [comment]
Great. You can add a pge with the rules as well, probably in a markdown table.

**Comment by darkred** [comment]
Ok, here: https://github.com/tophf/mpiv/wiki/MPIV's-host-rule-repository

**Comment by darkred** [comment]
@tophf 
I can no longer edit the wiki pages (no Edit/New Page buttons).

It seems like you have restricted wiki edits to collaborators only:

> To add/edit a rule here you need to become a collaborator (by submitting a PR) so if you don't want that, simply post the rule in Discussions.

Just to clarify:
In order someone to become a collaborator to a personal repo, [he must be invited](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository). 
Submitting PRs merged doesn't automatically turn him into a collaborator: he's just a *contributor*. 

I have submitted 4 PRs (merged), but have not been invited to become one.


---

I wanted to update the imdb repo rule for the new layout:
(to add `.ipc-lockup-overlay > .ipc-lockup-overlay__screen` to `"e"`)

<details>
<summary>from</summary>

```json
{"d": "imdb.com",
 "e": "img[src*='m.media-amazon.com'], .ipc-media--poster + .ipc-lockup-overlay *",
 "s": "return (node.tagName=='IMG' ? node : node.closest('.ipc-lockup-overlay').previousElementSibling.querySelector('img')).src.replace(/V1\\.?_.+?\\./, '')"
}
```
</details>

<details>
<summary>to</summary>

```json
{"d": "imdb.com",
 "e": "img[src*='m.media-amazon.com'], .ipc-media--poster + .ipc-lockup-overlay *, .ipc-lockup-overlay > .ipc-lockup-overlay__screen",
 "s": "return (node.tagName=='IMG' ? node : node.closest('.ipc-lockup-overlay').previousElementSibling.querySelector('img')).src.replace(/V1\\.?_.+?\\./, '')"
}
```

</details>

**Comment by tophf** [comment]
Thanks, I've added you so you should be able to change it yourself.

If anyone else wants to edit the wiki directly, post the changes you want to make in a [new discussion](https://github.com/tophf/mpiv/discussions/) and if you will participate more than just once in a blue moon I can send you an invite.

**Comment by darkred** [comment]
Thank you for adding me.

**Comment by tophf** [comment]
I think maybe these pages should be combined. The original seems to have a lot of useful tips.
