### ISSUE TITLE
imagefap

### ISSUE THREAD

**Issue by ANaPhOrAX** [tophf/mpiv#6]
hey, could you add imagefap support back?

edit: and motherless.com too?

**Comment by tophf** [comment]
No, but you can use the following rule by clicking it here (but first update the userscript)

```json
{"r": "imagefap\\.com/(image|photo)", "q": "[itemprop='contentUrl']"}
```

I've also added it in MPIV config's rule installer.

**Comment by tophf** [comment]
As for motherless.com, I don't see it in the original MPIV so you can try adding it yourself using the [documentation](https://w9p.co/userscripts/mpiv/host_rules.html) and other rules as an example.

**Comment by darkred** [comment]
Hi, @tophf 

I've noticed the following issues:
(using latest commit, currently https://github.com/tophf/mpiv/commit/a33710524f16419538336dbff25d1a515a9e11a9, with Chrome and TM/VM)

---

#### Regarding imagefap: 

the rule you gave above, doesn't work anymore:
there's no spinning cursor as I mouseover any imagefap image, nor any logging entry in console when I have the settings open.

---

#### Regarding motherless: 

For testing (in case it's related), I've also tried making the requested rules for motherless:

This, for images, works ok:
<sup>(the [one from the repo](https://w9p.co/userscripts/mpiv/manage_rules.html?edit=109) doesn't work)</sup>

```json
{"d": "motherless.com",
 "e": "*[data-mediatype='image'] > a",
 "q": "#media-media > div > a > img"
}
```

&nbsp;

Unfortunately, this, for videos, doesn't work:

```json
{"d": "motherless.com",
 "e": "[data-mediatype='video'] > a",
 "q": "return (e=doc.querySelector('#mediaspace_media > video'))? e.src : false"
}
```
Instead, when I mouseover any video thumbnail, there''s only the following plain error in Console:
![2020-03-15_135055](https://user-images.githubusercontent.com/723651/76700845-437b5200-66c4-11ea-9375-ec7e3b7d0a57.jpg)
but, there's no relevant `404` entry in 'Network' devtool.

By the way, could you please change the "File not found" part in the error message, 
to also contain which was the failed filename? (or it's a URL?)

**Comment by tophf** [comment]
The URL is the file URL, yes. As for the rules, I won't be looking into them unless it's a problem in the recent MPIV which isn't present in an earlier version.

**Comment by darkred** [comment]
> The URL is the file URL, yes.

Ok, so, could you please change the error from the plain `File not found` (from the original MPIV) 
to something more descriptive? Something like: 
`File URL not found in the DOM tree of the remote page` ?

I always found that error confusing in the original MPIV.

---

> As for the rules, I won't be looking into them unless it's a problem in the recent MPIV which isn't present in an earlier version.


The imagefap rule worked ok in version 1.1.6.
First non working  commit : https://github.com/tophf/mpiv/commit/783e248687d1c4972da3e3345949f1a3f6ed6f73

<details>
<summary>Regarding my motherless video rule</summary>

I found that I was using the wrong selector for `q`, because that would get the video URL from the remote page only after clicking the video to start playing, i.e. never.

Btw, the built-in rule works fine as it is, by adding
`*[data-mediatype='video'] > a` to their `"e"` attibute.
(I just updated it).

</details>

**Comment by tophf** [comment]
Should be fixed now.

**Comment by darkred** [comment]
Yes, thank you!
